#!/usr/bin/env python3
"""Generate INDEX.md — a clickable catalog of every PDF in the repo."""

from __future__ import annotations

import os
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKIP_DIRS = {".git", ".claude", ".cursor", "scripts", "__pycache__"}

CATEGORY_LABELS = {
    "01_programming": "Programming",
    "02_development_tools": "Development Tools",
    "03_generative_ai": "Generative AI",
    "04_presentations": "Presentations",
    "05_certifications": "Certifications",
    "06_interview_prep": "Interview Prep",
}

# Words that should remain lowercase in title case (unless first word)
_LOWERCASE_WORDS = {
    "a", "an", "the", "and", "but", "or", "for", "nor", "on", "at",
    "to", "by", "in", "of", "up", "as", "vs", "via",
}

# Known vendor/product prefixes to preserve casing
_VENDOR_PREFIXES = {
    "aws", "openai", "google", "anthropic", "nvidia", "neo4j",
    "langchain", "langgraph", "pytorch", "databricks", "mitre",
    "tiktok", "pwc", "github",
}

_VENDOR_DISPLAY = {
    "aws": "AWS",
    "openai": "OpenAI",
    "google": "Google",
    "anthropic": "Anthropic",
    "nvidia": "NVIDIA",
    "neo4j": "Neo4j",
    "langchain": "LangChain",
    "langgraph": "LangGraph",
    "pytorch": "PyTorch",
    "databricks": "Databricks",
    "mitre": "MITRE",
    "tiktok": "TikTok",
    "pwc": "PwC",
    "github": "GitHub",
}

# Common acronyms/initialisms to always uppercase
_ACRONYMS = {
    "ai", "ml", "llm", "api", "sql", "rag", "cag", "bi",
    "ui", "ux", "cli", "ci", "cd", "url", "http", "pdf", "gpt",
    "nlp", "cv", "qa", "kv", "rlhf", "lora",
}

# Words with specific mixed-case rendering
_MIXED_CASE = {
    "genai": "GenAI",
    "llms": "LLMs",
    "fastapi": "FastAPI",
    "vscode": "VS Code",
    "graphrag": "GraphRAG",
    "insurtech": "InsurTech",
    "deeplearning": "Deep Learning",
    "ds": "Data Science",
}


def human_name(filename: str) -> str:
    """Convert snake_case filename to a clean, readable title."""
    name = filename.replace(".pdf", "")
    # Split on underscores
    words = name.split("_")
    result = []
    for i, word in enumerate(words):
        lower = word.lower()
        if lower in _VENDOR_DISPLAY:
            result.append(_VENDOR_DISPLAY[lower])
        elif lower in _MIXED_CASE:
            result.append(_MIXED_CASE[lower])
        elif lower in _ACRONYMS:
            result.append(lower.upper())
        elif i > 0 and lower in _LOWERCASE_WORDS:
            result.append(lower)
        else:
            result.append(word.capitalize())
    return " ".join(result)


def collect_pdfs() -> dict[str, list[Path]]:
    """Walk the repo and group PDFs by their top-level category directory."""
    categories: dict[str, list[Path]] = {}
    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for f in sorted(filenames):
            if f.lower().endswith(".pdf"):
                rel = Path(dirpath).relative_to(REPO_ROOT) / f
                top = rel.parts[0]
                categories.setdefault(top, []).append(rel)
    return dict(sorted(categories.items()))


def generate_index() -> str:
    lines = [
        "# Full Index",
        "",
        "_Auto-generated by `scripts/generate_index.py`. Do not edit manually._",
        "",
    ]
    categories = collect_pdfs()
    total = sum(len(v) for v in categories.values())
    lines.append(f"**{total} PDFs** across {len(categories)} categories.\n")

    for cat, pdfs in categories.items():
        label = CATEGORY_LABELS.get(cat, cat)
        lines.append(f"## {label} ({len(pdfs)})\n")

        # Group by subdirectory
        subdirs: dict[str, list[Path]] = {}
        for p in pdfs:
            parts = p.parts
            subdir = parts[1] if len(parts) > 2 else ""
            subdirs.setdefault(subdir, []).append(p)

        for subdir in sorted(subdirs.keys()):
            sub_pdfs = subdirs[subdir]
            if subdir:
                heading_words = []
                for w in subdir.split("_"):
                    lower = w.lower()
                    if lower in _VENDOR_DISPLAY:
                        heading_words.append(_VENDOR_DISPLAY[lower])
                    elif lower in _MIXED_CASE:
                        heading_words.append(_MIXED_CASE[lower])
                    elif lower in _ACRONYMS:
                        heading_words.append(lower.upper())
                    else:
                        heading_words.append(w.capitalize())
                lines.append(f"### {' '.join(heading_words)}\n")
            for pdf in sorted(sub_pdfs):
                name = human_name(pdf.name)
                link = str(pdf).replace(" ", "%20")
                lines.append(f"- [{name}]({link})")
            lines.append("")

    return "\n".join(lines)


def update_readme_count(total: int) -> None:
    """Patch the PDF count in README.md to keep it in sync."""
    readme = REPO_ROOT / "README.md"
    text = readme.read_text()
    updated = re.sub(
        r"\d+ PDFs",
        f"{total} PDFs",
        text,
        count=1,
    )
    if updated != text:
        readme.write_text(updated)
        print(f"  README.md count updated to {total}")


if __name__ == "__main__":
    index = generate_index()
    out = REPO_ROOT / "INDEX.md"
    out.write_text(index)
    total = sum(len(v) for v in collect_pdfs().values())
    update_readme_count(total)
    print(f"Generated {out} ({total} PDFs)")
