#!/usr/bin/env python3
"""Generate INDEX.md — a clickable catalog of every PDF in the repo."""

import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKIP_DIRS = {".git", ".claude", ".cursor", "scripts", "__pycache__"}

CATEGORY_LABELS = {
    "01_programming": "Programming",
    "02_development_tools": "Development Tools",
    "03_generative_ai": "Generative AI",
    "04_presentations": "Presentations",
    "05_certifications": "Certifications",
    "06_interview_prep": "Interview Prep",
}


def human_name(filename: str) -> str:
    """Convert snake_case filename to a readable title."""
    name = filename.replace(".pdf", "")
    name = name.replace("_", " ")
    return name


def collect_pdfs() -> dict[str, list[Path]]:
    """Walk the repo and group PDFs by their top-level category directory."""
    categories: dict[str, list[Path]] = {}
    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for f in sorted(filenames):
            if f.lower().endswith(".pdf"):
                rel = Path(dirpath).relative_to(REPO_ROOT) / f
                top = rel.parts[0]
                categories.setdefault(top, []).append(rel)
    return dict(sorted(categories.items()))


def generate_index() -> str:
    lines = [
        "# 📚 Full Index",
        "",
        "_Auto-generated by `scripts/generate_index.py`. Do not edit manually._",
        "",
    ]
    categories = collect_pdfs()
    total = sum(len(v) for v in categories.values())
    lines.append(f"**{total} PDFs** across {len(categories)} categories.\n")

    for cat, pdfs in categories.items():
        label = CATEGORY_LABELS.get(cat, cat)
        lines.append(f"## {label} ({len(pdfs)})\n")

        # Group by subdirectory
        subdirs: dict[str, list[Path]] = {}
        for p in pdfs:
            parts = p.parts
            subdir = parts[1] if len(parts) > 2 else ""
            subdirs.setdefault(subdir, []).append(p)

        for subdir in sorted(subdirs.keys()):
            sub_pdfs = subdirs[subdir]
            if subdir:
                lines.append(f"### {subdir.replace('_', ' ').title()}\n")
            for pdf in sorted(sub_pdfs):
                name = human_name(pdf.name)
                link = str(pdf).replace(" ", "%20")
                lines.append(f"- [{name}]({link})")
            lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    index = generate_index()
    out = REPO_ROOT / "INDEX.md"
    out.write_text(index)
    print(f"✅ Generated {out} ({sum(len(v) for v in collect_pdfs().values())} PDFs)")
